#!/bin/sh
set -e

# prefer user supplied CFLAGS, but default to our PHP_CFLAGS
: ${CFLAGS:=$PHP_CFLAGS}
: ${CPPFLAGS:=$PHP_CPPFLAGS}
: ${LDFLAGS:=$PHP_LDFLAGS}
export CFLAGS CPPFLAGS LDFLAGS

srcExists=
if [ -d /usr/src/php ]; then
	srcExists=1
fi
docker-php-source extract
if [ -z "$srcExists" ]; then
	touch /usr/src/php/.docker-delete-me
fi

cd /usr/src/php/ext

usage() {
	echo "usage: $0 ext-name [ext-name ...]"
	echo "   ie: $0 ssh2 json"
	echo
	echo 'if custom ./configure arguments are necessary, see docker-php-ext-configure'
	echo
	echo 'Possible values for ext-name: ssh2'
	echo
}

opts="$(getopt -o 'h' --long 'help' -- "$@" || { usage >&2 && false; })"
eval set -- "$opts"

j=1
while true; do
	flag="$1"
	shift
	case "$flag" in
		--help|-h|'-?') usage && exit 0 ;;
		--) break ;;
		*)
			{
				echo "error: unknown flag: $flag"
				usage
			} >&2
			exit 1
			;;
	esac
done

exts=
deps=
for ext; do
	if [ -z "$ext" ]; then
		continue
	fi
    case "$ext" in
        ssh2)
            exts="$exts ssh2-1.1.2"
            deps="$deps ssh2-dev"
            ;;
    esac
done

if [ -z "$exts" ]; then
	usage >&2
	exit 1
fi

pm='unknown'
if [ -e /lib/apk/db/installed ]; then
	pm='apk'
fi

apkDel=
if [ "$pm" = 'apk' ]; then
	if [ -n "$PHPIZE_DEPS" ]; then
		if apk info --installed .phpize-deps-configure > /dev/null; then
			apkDel='.phpize-deps-configure'
		elif ! apk info --installed .phpize-deps > /dev/null; then
			apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS
			apkDel='.phpize-deps'
		fi
	fi
    apk add --no-cache --virtual .build-deps $deps
    apkDel="$apkDel .build-deps"
fi

for ext in $exts; do
    pecl install $ext
done

if [ "$pm" = 'apk' ] && [ -n "$apkDel" ]; then
	apk del $apkDel
fi

if [ -e /usr/src/php/.docker-delete-me ]; then
	docker-php-source delete
fi
