# vim: ts=4 sw=4 sts=4 retab

name: Deploy

on:
    - push

jobs:
    deploy:
        name: Deploy to dockerhub
        runs-on: ubuntu-latest
        steps:
            - name: Dockerhub login
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Run deploy script
              run: ./deploy.sh
